### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by OhMyGuus** [OhMyGuus/I-Dont-Care-About-Cookies#7]
**Todo**
- [ ]  Update manifest version from V2 to V3 & test
- [ ] Write installation guides
- [ ] Decide on the name & logo changes to make it clear that it's a non-avast version in the ff store. 
 (Was thinking of I Don't Care About Cookies (debloated)  or something like that but not sure what ff & chrome allowed)
- [ ] Publish on Mozilla & chrome webstore if allowed 

If someone has suggestions or things like that this is the place 👍

**Comment by winskil** [comment]
Installing the extension on Firefox:
Download the .xpi from releases
<img width="1272" alt="Screenshot 2022-09-16 at 18 20 25" src="https://user-images.githubusercontent.com/44670482/190674472-bd0265fa-0e3d-494e-afba-0656ab9b3e6c.png">
<img width="1238" alt="Screenshot 2022-09-16 at 18 20 59" src="https://user-images.githubusercontent.com/44670482/190674503-bfefdf2d-44ba-4556-a978-cfd5ae551acc.png">
Type `about:addons` into the URL bar
Click the gear wheel icon and click `Install Add-on From File...`
<img width="1920" alt="Screenshot 2022-09-16 at 18 22 06" src="https://user-images.githubusercontent.com/44670482/190674632-56c4ffe5-92fe-4a55-abde-3481f91544a4.png">
Locate the corresponding .xpi file
<img width="425" alt="Screenshot 2022-09-16 at 18 22 44" src="https://user-images.githubusercontent.com/44670482/190674802-a37df67d-e362-4850-89ad-1bc31ff6ee40.png">
Install the extension by clicking `Add`

**Comment by Mystqr4** [comment]
Maybe the correct name should be "I don't care about Cookies or Avast" hahaha
Just kidding but some sort on name and logo change would be great.

Bring back the additional options to "report a cookie warning" and also an option to "disable extension on _____ website here_____.com"

**Comment by OhMyGuus** [comment]
> Maybe the correct name should be "I don't care about Cookies or Avast" hahaha Just kidding but some sort on name and logo change would be great.
> 
> Bring back the additional options to "report a cookie warning" and also an option to "disable extension on _____ website here_____.com"

Hahahaha love that name 

Oh and thanks for the notify about the report & disable will fix that indeed :)

**Comment by winskil** [comment]
You're welcome! I have a Chrome tutorial ready as well, but it still has the `Manifest version 2 is deprecated, and support will be removed in 2023.` warning so I will add it here when it's fixed (currently looking through the V3 migration docs)

**Comment by winskil** [comment]
Installing the extension on Chrome

Download the .zip from releases
<img width="1272" alt="" src="https://user-images.githubusercontent.com/44670482/190684203-12aceee2-09c0-4cb4-a61f-3b49d774d9b2.png">
<img width="1109" alt="" src="https://user-images.githubusercontent.com/44670482/190684393-735809a0-ca1f-45d1-9cac-7cb2266cd94a.png">

Type `chrome://extensions` into the URL bar
Enable developer mode
<img width="1920" alt="" src="https://user-images.githubusercontent.com/44670482/190685064-302e4574-a2da-4c29-99cb-fa028aee4d17.png">
Drag the .zip to the extensions page
<img width="1920" alt="" src="https://user-images.githubusercontent.com/44670482/190685900-bd28e424-6436-49a8-a2d7-acbe4dac048e.png">
<img width="1920" alt="" src="https://user-images.githubusercontent.com/44670482/190686048-18f80156-ac6a-4da6-b713-66248b26e8e3.png">


You may notice that the extension has errors. Why?

Chrome stops supporting Manifest V2 in 2023 (which the extension currently uses).
This will be fixed in the future release so for now you can ignore it.

**Comment by maricn** [comment]
Maybe a question here (and a statement), coming from someone who cares about cookies - cares to have the least of them tracking cookies used. Is this extension just plainly going the "Accept All Cookies" route or it attempts to "Reject All Cookies" (or do its best to achieve minimum cookies stored)?

I always found the "I don't care" part confusing - does the extension just do whatever is necessary to remove the banner/pop-up? If it does its best to minimize the amount of cookies used, I'd be welcoming altogether new name, such as "Cookie? No, thank you!", "Cookie rejecter", "Reject All Cookies" or whatever pun you can think of in that direction...

**Comment by Mystqr4** [comment]
One thing that is probably more important and easily fixed is the details on the extension in Firefox such as the author which still displays "Daniel Kladnik @ kiboke studio" as well as the version numbering would be great if it where somewhat different I guess.

**Comment by winskil** [comment]
@maricn Copied this from the original site
```In most cases, it just blocks or hides cookie related pop-ups. When it's needed for the website to work properly, it will automatically accept the cookie policy for you (sometimes it will accept all and sometimes only necessary cookie categories, depending on what's easier to do). It doesn't delete cookies. ```

**Comment by maricn** [comment]
> @maricn Copied this from the original site `In most cases, it just blocks or hides cookie related pop-ups. When it's needed for the website to work properly, it will automatically accept the cookie policy for you (sometimes it will accept all and sometimes only necessary cookie categories, depending on what's easier to do). It doesn't delete cookies. `

_Thank you for sharing that quote. I remember it well, and was repeatedly sorry for the (afaik) lack of public issue tracker and open source nature of the project to address it._

Unless the website is in breach of ePrivacy, GDPR and/or other local regulations (which btw you may assume exactly all of them are, just a matter of extent; however let's assume they're not) - they shouldn't store any cookies that are strictly not necessary. That means just killing a pop-up should be enough to stop the website from storing any tracking cookies.

What I hope can be improved in a fork of that project (perhaps over time, not immediately) is to avoid accepting all cookies. Instead of doing "what's easier", go the hard way for improving user privacy. That's just my dream, I felt this could be a good moment to share it, but I don't promise involvement in developing the extension, so please feel free to ignore my POV. :)

**Comment by ikanakova** [comment]
As for the name, I think we shouldn't stick to the original one, because [i]I don't care about cookies[/i] can evoke that we don't care if we allow all cookies and let be snooped on.

**Comment by DamianGuth** [comment]
> @maricn Copied this from the original site `In most cases, it just blocks or hides cookie related pop-ups. When it's needed for the website to work properly, it will automatically accept the cookie policy for you (sometimes it will accept all and sometimes only necessary cookie categories, depending on what's easier to do). It doesn't delete cookies. `

In my experience the extension mostly accepted all cookies. I think (if wanted) we can improve on that while (or after) cleaning up the original code.

**Comment by osdiab** [comment]
IDGAF About Cookies

**Comment by mll0** [comment]
> What I hope can be improved in a fork of the original project (perhaps over time, not immediately) is to avoid accepting all cookies. Instead of doing "what's easier", go the hard way for improving user privacy. That's just my dream, I felt this could be a good moment to share it, but I don't promise involvement in developing the extension, so please feel free to ignore my POV. :)

Agreed. It seems it's the path taken by Consent-O-Matic, but after a few hours of surf, many cookie popups are still visible.
So maybe the present fork of IDCAC, associated with some cookie mangement addon I have yet to find, would be the right choice.

**Comment by holdit** [comment]
A mix of _Consent-O-Matic_ and _I don't care about cookies_ would be perfect. The extension could:

1. Try to uncheck all permissions and then submit the form (like Consent-O-Matic does).
2. When the above isn't possible (eg: if the extension doesn't support the popup), deny/reject all cookies.
3. If it's not possible to reject all, then accept them so the popup goes away.

Since some users wouldn't like the option to accept cookies, a setting could be added to disable these "fallbacks", giving the user the chance to leave the site without accepting any cookies.

**Comment by maricn** [comment]
jsyk according to the latest rulings (at least per GDPR and ePrivacy) websites shouldn't make it any harder for the user to reject than to accept non essential cookies.. also by default they should be unchecked.. ofc that doesn't mean there will be no websites in violation and/or transition to that behavior..

**Comment by Sly-Little-Fox** [comment]
> jsyk according to the latest rulings (at least per GDPR and ePrivacy) websites shouldn't make it any harder for the user to reject than to accept non essential cookies.. also by default they should be unchecked.. ofc that doesn't mean there will be no websites in violation and/or transition to that behavior..

A LOT of sites only display the accept all button and options, where everything is checked by default.

**Comment by appeasementPolitik** [comment]
About the rewrite and cleanup, I think it might be useful to rename `common6.js`, `common3.js` to something like  `6_cookies.js`, `3_localstorage.js` to make it easier to locate the proper file to edit.

**Comment by OhMyGuus** [comment]
> About the rewrite and cleanup, I think it might be useful to rename `common6.js`, `common3.js`, `common5.js` to something like `6_cookies.js`, `3_localstorage.js`, `5_mouseclick.js` to make it easier to locate the proper file to edit.

Good idea!

**Comment by appeasementPolitik** [comment]
After looking at the part that loads the `common(n).js` files, (line 476 of `context-menu.js`) it looks like renaming the files to a better name is not possible, as the `executeScript` function needs a full file name to load. There could be something like an index with the numbers that belong to the file names in order to fix it, but this looks too complex.  Maybe something like a contributors guide which explains what each file does is a better idea.

**Comment by OhMyGuus** [comment]
> After looking at the part that loads the `common(n).js` files, (line 476 of `context-menu.js`) it looks like renaming the files to a better name is not possible, as the `executeScript` function needs a full file name to load. There could be something like an index with the numbers that belong to the file names in order to fix it, but this looks too complex. Maybe something like a contributors guide which explains what each file does is a better idea.

Did already some things u suggested in #223 , will create a guide as well this week 😄
Planning to do some more changes later as well like fixing the duplicated blockrules (manifestv2 & manifestv3 rules)

**Comment by appeasementPolitik** [comment]
Looks good 👍, much cleaner

**Comment by appeasementPolitik** [comment]
In `rules.js`, in the `blockUrls` part, there are a lot of `q: false` and `e: false`. Maybe there's a way to set false as the default value for q and e so that they can be removed?

**Comment by Deedikjupijn** [comment]
It would be really nice if you could set the addon (in some kind of settings tab because I think some people maybe don't want it) to display one pop up with it asking to keep the banner and let you answer it or remove the entire banner (with the information displayed about if it will accept or reject the cookies). so like a  popup that has 2 buttons first one: Remove cookies banner and accept (or reject in the cases that would be possible) cookies. 2nd button will be: leave banner open and choose yourself.

**Comment by nicolaasjan** [comment]
Request:
Provide a link to a Manifest v2 `.crx` file on [Releases](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/releases) while Google still permits them.

Reason:
Manifest v3 version is still somewhat slow and buggy.

**Comment by appeasementPolitik** [comment]
Also, code starting from 250 and line 284 in `background.js` is duplicate code, it might be possible to make a function for it

**Comment by appeasementPolitik** [comment]
Another idea, add issue tags for the used browser, so people that want to make rules for a specific browser can easily see what issue they have to click

**Comment by Sly-Little-Fox** [comment]
> Another idea, add issue tags for the used browser, so people that want to make rules for a specific browser can easily see what issue they have to click (could also automatically tag for mobile)
> 
> Edit: automatic NSFW tagging could also be possible by looking up the domain name on a list

Yandex's or NextDNS's database could be used. Or, alternatively, any anti-NSFW uBlock filter.

**Comment by appeasementPolitik** [comment]
Another idea, linking duplicate issues together:

https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/1027#issuecomment-1341651294

**Comment by appeasementPolitik** [comment]
I think `common.css` could also be extended to allow rules like `.modal-open{overflow:unset !important`, which is a rule that would solve a lot of issues instantly, and also completely removes the need for commons rule 14. It should not break any websites, but if it does maybe a website blacklist could be implemented for these rules as well.

**Comment by KazimirPodolski** [comment]
1. Is it sensible to kill _any_ footer-hanging block containing "cookies", "use" and a button/link "accept"? As a measure to reduce site-specific filters.
2. Is there a better system for collecting and storing filters, rather than by-site filters in git? Look at SponsorBlock - I think they have self-moderated system with users submitting advertising blocks of YouTube videos. This one can have the same, but for per-site selector, and in some DB, probably.

**Comment by krystian3w** [comment]
What I miss is that the pop-up report remembers the entry text - if something closes it, I lose the text.

Apparently in Firefox, maybe opening in the sidebar will work: https://addons.mozilla.org/en-US/firefox/addon/open_in_sidebar/

**Comment by Mystqr4** [comment]
Is there any progress on the Pale moon version for this. I find Basilisk and Pale moon are making some nice progress of late and it would be nice to have this extension for those browsers.

Has there been any progress on the Rewrite. I know both of these tasks are huge and would like to know if you are okay with everything. Sadly I do not have any skills to add to this project so I hope you are getting some sort of support with this.
It would be a shame for this extension to lose traction as it has been pretty great so far.

**Comment by krystian3w** [comment]
It would still be possible to implement in this thread to hide the ideas implemented, this can be done by the person what has "write" permissions in the repository or the author of the comment:
